package ch.conceptforge.masuperapplicationtropgenial;
// Generated 22 mars 2018 15:05:29 by Hibernate Tools 4.3.1



/**
 * Joueur generated by hbm2java
 */
public class Joueur  implements java.io.Serializable {


     private long id;
     private Double budget;
     private String motdepasse;
     private String nom;
     private String pseudo;

    public Joueur() {
    }

	
    public Joueur(long id) {
        this.id = id;
    }
    public Joueur(long id, Double budget, String motdepasse, String nom, String pseudo) {
       this.id = id;
       this.budget = budget;
       this.motdepasse = motdepasse;
       this.nom = nom;
       this.pseudo = pseudo;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Double getBudget() {
        return this.budget;
    }
    
    public void setBudget(Double budget) {
        this.budget = budget;
    }
    public String getMotdepasse() {
        return this.motdepasse;
    }
    
    public void setMotdepasse(String motdepasse) {
        this.motdepasse = motdepasse;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPseudo() {
        return this.pseudo;
    }
    
    public void setPseudo(String pseudo) {
        this.pseudo = pseudo;
    }




}


